### ISSUE TITLE
为什么总是报错，AssertionError: bin_size should be divisible by 360.

### ISSUE THREAD

**Issue by ghost** [PENGZhaoqing/Hog-feature#3]
代码参数没改，bin_size是8，也能被360整除，为何却不能跑呢？工程自带的图片也不可以，什么原因啊？

**Comment by HoldYourFire** [comment]
@PENGZhaoqing ，大神来解答一下啊

**Comment by hanshan1** [comment]
> 已解决，

> 已解决，是双斜杠的问题

老哥，你是怎么解决的啊，我有同样的问题

**Comment by maodoudabai** [comment]
> 已解决，是双斜杠的问题

请问您是怎么解决的，多谢回复！

**Comment by csitaula** [comment]
Did anyone solved this issue? bin_size should be divisible by 360.

**Comment by freedom9393** [comment]
Here is the solution: https://github.com/PENGZhaoqing/Hog-feature/commit/2c47bf143ef51f4579d1eef4cdddf8196bb09531
